# Generated by Django 3.2.3 on 2021-06-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0002_auto_20210603_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='declare',
            field=models.BooleanField(default=False),
        ),
    ]
