# Generated by Django 3.2.3 on 2021-06-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polling', '0003_candidate_declare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='sno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
